import AppKit

/// Everything that was on the pasteboard: every item with every representation.
struct ClipboardSnapshot: Sendable {
    var items: [[NSPasteboard.PasteboardType: Data]]
}

/// Saves and restores the pasteboard around a paste without losing images, files or rich text.
@MainActor
struct ClipboardManager {
    /// nspasteboard.org markers so clipboard-history apps skip our temporary write.
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    func snapshot() -> ClipboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            var representations: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { representations[type] = data }
            }
            return representations
        }
        return ClipboardSnapshot(items: items)
    }

    /// Puts `text` on the pasteboard and returns the resulting change count.
    func write(_ text: String, transient: Bool) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if transient {
            item.setData(Data(), forType: Self.transientType)
            item.setData(Data(), forType: Self.autoGeneratedType)
        }
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    /// Restores `snapshot` unless someone else changed the pasteboard after our write.
    @discardableResult
    func restore(_ snapshot: ClipboardSnapshot, ifChangeCountIs expected: Int) -> Bool {
        guard pasteboard.changeCount == expected else { return false }
        pasteboard.clearContents()
        let items = snapshot.items.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: type) }
            return item
        }
        if !items.isEmpty { pasteboard.writeObjects(items) }
        return true
    }
}
